#[Backend]
backend = "auto"
transition_mode = "geo"

#[Smoothing]
smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

#[Time-based config]
night_temp = 3900
day_temp = 6300
night_gamma = 60
day_gamma = 80
update_interval = 60

#[Geolocation]
latitude = -23.5475
longitude = -46.63611
